version: '2.1'
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: 'cimg/python:3.10.2'
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - snyk/scan
          additional-arguments: --all-projects
          monitor-on-build: true
workflows: null